version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: fs-innovation-day-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbitmq_secret_string"
      RABBITMQ_NODENAME: rabbitmq
    volumes:
      # - './_datastorage/rabbitmq/data/:/var/lib/rabbitmq/'
      - "./_datastorage/rabbitmq/log/:/var/log/rabbitmq"
      - "./_datastorage/rabbitmq/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./_datastorage/rabbitmq/definitions/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: "redis:latest"
    container_name: fs-innovation-day-redis
    command: redis-server --requirepass mypassword
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: fs-innovation-day-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  mongodb:
    image: "mongo:latest"
    container_name: fs-innovation-day-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - 27017:27017
    restart: unless-stopped
