version: "3.9"
services:
  redis:
      image: "redis:latest"
      command: redis-server --requirepass mypassword
      ports:
      - "6379:6379"

  postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_PASSWORD: mypassword
      ports:
      - "5432:5432"
